# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  # Azure DevOps variables are transformed into environment variables, with these variables we
  # avoid the first time experience and telemetry to speed up the build.
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

steps:

#- task: UseDotNet@2
#  displayName: 'Use .NET Core sdk 3'
#  inputs:
#    packageType: sdk
#    version: 3.0.100
#    installationPath: $(Agent.ToolsDirectory)/dotnet

#- task: DotNetCoreInstaller@0
#  inputs:
#    version: '3.0.100-preview9-014004'

- script: dotnet restore
  displayName: 'Restore packages'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

#- task: WhiteSource Bolt@19
#  inputs:
#    advance: true

- powershell: .\test.ps1 -Verbose
  displayName: 'Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest' # Options: JUnit, NUnit, VSTest, xUnit
    testResultsFiles: '**/TEST-*.xml'
    #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
    #mergeTestResults: true # Optional
    #testRunTitle: # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    publishRunAttachments: false # Optional

#- task: PublishBuildArtifacts@1