# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  # Azure DevOps variables are transformed into environment variables, with these variables we
  # avoid the first time experience and telemetry to speed up the build.
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

steps:

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 3.1.x'
  inputs:
    packageType: sdk
    version: 3.1.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: OpenGraphTilemaker.sln

- task: DotNetCoreCLI@2
  displayName: 'dotnet test $(buildConfiguration)'
  inputs:
    command: 'test'
    arguments: '--no-build --configuration "Release" --logger "trx;LogFileName=TEST-results.xml" --collect "Code coverage"'

#- task: NuGetCommand@2
#  displayName: 'Restore NuGet packages'
#  inputs:
#    command: 'restore'
#    restoreSolution: '**/*.sln'

#- task: DotNetCoreCLI@2
#  displayName: 'dotnet build $(buildConfiguration)'
#  inputs:
#    command: 'build'

#- task: DotNetCoreCLI@2
#  displayName: 'dotnet test $(buildConfiguration)'
#  inputs:
#    command: 'test'

#- script: dotnet restore
#  displayName: 'dotnet restore'

#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'

#- task: WhiteSource Bolt@19
#  inputs:
#    advance: true

#- powershell: .\test.ps1 -Verbose
#  displayName: 'dotnet test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest' # Options: JUnit, NUnit, VSTest, xUnit
    testResultsFiles: '**/TEST-*.xml'
    #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
    #mergeTestResults: true # Optional
    #testRunTitle: # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    publishRunAttachments: false # Optional
